# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/postcover/'),
        ),
    ]
