# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_format',
            field=models.CharField(choices=[('ST', 'Standard'), ('QU', 'Quote'), ('CH', 'Chat'), ('ST', 'Status'), ('MU', 'Music'), ('VI', 'Video'), ('GA', 'Gallry')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_cover',
            field=models.ImageField(blank=True, null=True, upload_to='postcover'),
        ),
    ]
